/**
 * Document Service - Export research reports to PDF/DOCX
 */

import { researchService, ResearchResult } from './researchService';

export interface DocumentExportOptions {
  format: 'pdf' | 'docx' | 'html';
  includeMetadata: boolean;
  includeCompetitors: boolean;
}

class DocumentService {
  /**
   * Export research to HTML format (foundation for PDF/DOCX conversion)
   */
  exportToHTML(research: ResearchResult): string {
    const { request, executiveSummary, marketAnalysis, swot, keyInsights, recommendations, generatedAt } = research;

    return `
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Market Research Report - ${request.topic}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            margin: 40px;
        }
        h1 { color: #2c3e50; border-bottom: 3px solid #3498db; padding-bottom: 10px; }
        h2 { color: #34495e; margin-top: 30px; }
        h3 { color: #7f8c8d; }
        .metadata { background-color: #ecf0f1; padding: 15px; border-radius: 5px; margin-bottom: 20px; }
        .swot-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-top: 20px; }
        .swot-box { border: 2px solid #3498db; border-radius: 5px; padding: 15px; }
        .strengths { border-left: 5px solid #27ae60; }
        .weaknesses { border-left: 5px solid #e74c3c; }
        .opportunities { border-left: 5px solid #f39c12; }
        .threats { border-left: 5px solid #c0392b; }
        ul { margin: 10px 0; padding-left: 20px; }
        .footer { margin-top: 50px; padding-top: 20px; border-top: 1px solid #bdc3c7; font-size: 12px; color: #7f8c8d; }
    </style>
</head>
<body>
    <h1>Market Research Report</h1>
    <h2>${request.topic}</h2>

    <div class="metadata">
        <p><strong>Target Audience:</strong> ${request.targetAudience}</p>
        <p><strong>Geographic Focus:</strong> ${request.geographicFocus}</p>
        ${request.competitors && request.competitors.length > 0 ? `<p><strong>Competitors Analyzed:</strong> ${request.competitors.join(', ')}</p>` : ''}
        <p><strong>Generated:</strong> ${generatedAt || new Date().toISOString()}</p>
    </div>

    ${executiveSummary ? `
    <h2>Executive Summary</h2>
    <p>${executiveSummary}</p>
    ` : ''}

    ${marketAnalysis ? `
    <h2>Market Analysis</h2>
    <p>${marketAnalysis.replace(/\n/g, '<br>')}</p>
    ` : ''}

    ${swot ? `
    <h2>SWOT Analysis</h2>
    <div class="swot-grid">
        <div class="swot-box strengths">
            <h3>Strengths</h3>
            <ul>${swot.strengths.map((s) => `<li>${s}</li>`).join('')}</ul>
        </div>
        <div class="swot-box weaknesses">
            <h3>Weaknesses</h3>
            <ul>${swot.weaknesses.map((w) => `<li>${w}</li>`).join('')}</ul>
        </div>
        <div class="swot-box opportunities">
            <h3>Opportunities</h3>
            <ul>${swot.opportunities.map((o) => `<li>${o}</li>`).join('')}</ul>
        </div>
        <div class="swot-box threats">
            <h3>Threats</h3>
            <ul>${swot.threats.map((t) => `<li>${t}</li>`).join('')}</ul>
        </div>
    </div>
    ` : ''}

    ${keyInsights && keyInsights.length > 0 ? `
    <h2>Key Insights</h2>
    <ol>${keyInsights.map((insight) => `<li>${insight}</li>`).join('')}</ol>
    ` : ''}

    ${recommendations && recommendations.length > 0 ? `
    <h2>Recommendations</h2>
    <ul>${recommendations.map((rec) => `<li>${rec}</li>`).join('')}</ul>
    ` : ''}

    <div class="footer">
        <p>This report was generated by Formative.AI</p>
        <p>Report ID: ${research.id}</p>
    </div>
</body>
</html>
    `;
  }

  /**
   * Export research to plain text
   */
  exportToText(research: ResearchResult): string {
    const { request, executiveSummary, marketAnalysis, swot, keyInsights, recommendations, generatedAt } = research;

    let text = `MARKET RESEARCH REPORT
${request.topic}
${'='.repeat(60)}\n`;

    text += `\nMETADATA:\n`;
    text += `Target Audience: ${request.targetAudience}\n`;
    text += `Geographic Focus: ${request.geographicFocus}\n`;
    if (request.competitors && request.competitors.length > 0) {
      text += `Competitors: ${request.competitors.join(', ')}\n`;
    }
    text += `Generated: ${generatedAt || new Date().toISOString()}\n`;

    if (executiveSummary) {
      text += `\nEXECUTIVE SUMMARY\n${'='.repeat(60)}\n${executiveSummary}\n`;
    }

    if (marketAnalysis) {
      text += `\nMARKET ANALYSIS\n${'='.repeat(60)}\n${marketAnalysis}\n`;
    }

    if (swot) {
      text += `\nSWOT ANALYSIS\n${'='.repeat(60)}\n`;
      text += `\nStrengths:\n${swot.strengths.map((s) => `  - ${s}`).join('\n')}\n`;
      text += `\nWeaknesses:\n${swot.weaknesses.map((w) => `  - ${w}`).join('\n')}\n`;
      text += `\nOpportunities:\n${swot.opportunities.map((o) => `  - ${o}`).join('\n')}\n`;
      text += `\nThreats:\n${swot.threats.map((t) => `  - ${t}`).join('\n')}\n`;
    }

    if (keyInsights && keyInsights.length > 0) {
      text += `\nKEY INSIGHTS\n${'='.repeat(60)}\n`;
      keyInsights.forEach((insight, i) => {
        text += `${i + 1}. ${insight}\n`;
      });
    }

    if (recommendations && recommendations.length > 0) {
      text += `\nRECOMMENDATIONS\n${'='.repeat(60)}\n`;
      recommendations.forEach((rec) => {
        text += `- ${rec}\n`;
      });
    }

    text += `\n\nGenerated by Formative.AI\nReport ID: ${research.id}\n`;

    return text;
  }

  /**
   * Export research to JSON
   */
  exportToJSON(research: ResearchResult): string {
    return JSON.stringify(research, null, 2);
  }

  /**
   * Generate filename for export
   */
  generateExportFilename(topic: string, format: 'pdf' | 'docx' | 'html' | 'txt' | 'json'): string {
    const timestamp = new Date().toISOString().split('T')[0];
    const sanitized = topic.replace(/[^a-z0-9]/gi, '_').toLowerCase();
    return `research_${sanitized}_${timestamp}.${format}`;
  }
}

export const documentService = new DocumentService();
